<a href="https://colab.research.google.com/github/AshleighGrant/DAT07-28-AG/blob/master/Class19.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [36]:
import pandas as pd
import numpy as np

In [4]:
df = pd.read_csv("/IMDB.csv")

In [5]:
df.head()

review sentiment
0  One of the other reviewers has mentioned that ...  positive
1  A wonderful little production. <br /><br />The...  positive
2  I thought this was a wonderful way to spend ti...  positive
3  Basically there's a family where a little boy ...  negative
4  Petter Mattei's "Love in the Time of Money" is...  positive

In [7]:
df["sentiment"].replace(["positive", "negative"], [1,0], inplace=True)

In [8]:
df.head()

review  sentiment
0  One of the other reviewers has mentioned that ...          1
1  A wonderful little production. <br /><br />The...          1
2  I thought this was a wonderful way to spend ti...          1
3  Basically there's a family where a little boy ...          0
4  Petter Mattei's "Love in the Time of Money" is...          1

In [9]:
import tensorflow as tf

In [10]:
from tensorflow import keras

In [11]:
from sklearn.model_selection import train_test_split

In [13]:
from keras.preprocessing.text import Tokenizer

In [14]:
from keras.preprocessing.sequence import pad_sequences

In [15]:
X = df["review"]
y = df["sentiment"]

In [16]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [17]:
tokenizer = Tokenizer(num_words=10000)

In [18]:
tokenizer.fit_on_texts(X_train)

In [19]:
tokenizer.word_index

{'the': 1,
 'and': 2,
 'a': 3,
 'of': 4,
 'to': 5,
 'is': 6,
 'br': 7,
 'in': 8,
 'it': 9,
 'i': 10,
 'this': 11,
 'that': 12,
 'was': 13,
 'as': 14,
 'for': 15,
 'with': 16,
 'movie': 17,
 'but': 18,
 'film': 19,
 'on': 20,
 'not': 21,
 'you': 22,
 'are': 23,
 'his': 24,
 'have': 25,
 'be': 26,
 'one': 27,
 'he': 28,
 'all': 29,
 'at': 30,
 'by': 31,
 'an': 32,
 'they': 33,
 'so': 34,
 'from': 35,
 'who': 36,
 'like': 37,
 'or': 38,
 'just': 39,
 'her': 40,
 'out': 41,
 'about': 42,
 'if': 43,
 "it's": 44,
 'has': 45,
 'there': 46,
 'some': 47,
 'what': 48,
 'good': 49,
 'more': 50,
 'very': 51,
 'when': 52,
 'up': 53,
 'no': 54,
 'time': 55,
 'my': 56,
 'even': 57,
 'she': 58,
 'would': 59,
 'which': 60,
 'only': 61,
 'story': 62,
 'really': 63,
 'see': 64,
 'their': 65,
 'had': 66,
 'can': 67,
 'me': 68,
 'well': 69,
 'were': 70,
 'we': 71,
 'than': 72,
 'much': 73,
 'bad': 74,
 'been': 75,
 'do': 76,
 'get': 77,
 'great': 78,
 'also': 79,
 'will': 80,
 'other': 81,
 'into': 82,
 'p

In [20]:
train_sequences = tokenizer.texts_to_sequences(X_train)
test_sequences = tokenizer.texts_to_sequences(X_test)

In [22]:
train_sequences[0]

[197,
 48,
 10,
 801,
 2160,
 534,
 302,
 1,
 107,
 1907,
 2038,
 4324,
 6550,
 2,
 815,
 4844,
 12,
 1,
 227,
 1,
 6190,
 79,
 782,
 53,
 52,
 22,
 101,
 4,
 1,
 27,
 2009,
 102,
 36,
 25,
 34,
 119,
 1130,
 12,
 9,
 6,
 2366,
 1190,
 5,
 454,
 48,
 552,
 5,
 92,
 33,
 23,
 39,
 916,
 400,
 15,
 1,
 166,
 5,
 2993,
 24,
 4359,
 20,
 3,
 2945,
 12,
 45,
 75,
 221,
 73,
 126,
 8,
 81,
 3155,
 195,
 20,
 239,
 2,
 1,
 447,
 7,
 7,
 10,
 205,
 4982,
 144,
 21,
 63,
 27,
 15,
 74,
 365,
 302,
 3,
 19,
 18,
 9,
 205,
 26,
 307,
 12,
 14,
 1,
 115,
 439,
 2,
 14,
 1,
 1704,
 615,
 70,
 424,
 381,
 10,
 89,
 118,
 48,
 112,
 370,
 33,
 35,
 18,
 43,
 10,
 13,
 92,
 485,
 6830,
 15,
 3,
 364,
 1182,
 61,
 8,
 1,
 470,
 216,
 1014,
 5,
 4160,
 8,
 3,
 174,
 4,
 34,
 440,
 697,
 623,
 12,
 3748,
 237,
 111,
 848,
 35,
 170,
 30,
 219,
 197,
 1,
 428,
 367,
 55,
 3765,
 3,
 278,
 7,
 7,
 157,
 1707,
 187,
 6,
 1,
 727,
 1935,
 1,
 1200,
 4,
 2946,
 3749,
 1828,
 2,
 147,
 144,
 3,
 228,
 4,
 3,
 

In [23]:
train_sequences[16]

[1094,
 29,
 1,
 1355,
 104,
 37,
 1,
 6428,
 1413,
 2,
 181,
 8,
 3702,
 12,
 23,
 9,
 6,
 1794,
 12,
 11,
 27,
 6,
 34,
 3450,
 7,
 7,
 46,
 6,
 54,
 378,
 8,
 9,
 18,
 378,
 6,
 187,
 4,
 568,
 1,
 322,
 12,
 9,
 199,
 495,
 48,
 405,
 101,
 42,
 9,
 1,
 355,
 76,
 21,
 211,
 77,
 341,
 16,
 65,
 807,
 18,
 1129,
 1,
 807,
 38,
 1,
 355,
 23,
 105,
 14,
 211,
 203,
 38,
 360,
 2,
 1,
 807,
 23,
 21,
 105,
 14,
 1829,
 7,
 7,
 9,
 1981,
 16,
 630,
 8448,
 86,
 27,
 250,
 124,
 3,
 1720,
 148,
 60,
 97,
 25,
 470,
 5,
 143,
 159,
 4762,
 12,
 58,
 13,
 360,
 7,
 7,
 1,
 17,
 6,
 243,
 4,
 1449,
 4,
 55,
 27,
 547,
 1761,
 157,
 547,
 48,
 2699,
 1146,
 58,
 1082,
 58,
 536,
 58,
 6,
 407,
 162,
 5,
 359,
 2699,
 1146,
 58,
 6369,
 7990,
 378]

In [25]:
tokenizer.word_index

{'the': 1,
 'and': 2,
 'a': 3,
 'of': 4,
 'to': 5,
 'is': 6,
 'br': 7,
 'in': 8,
 'it': 9,
 'i': 10,
 'this': 11,
 'that': 12,
 'was': 13,
 'as': 14,
 'for': 15,
 'with': 16,
 'movie': 17,
 'but': 18,
 'film': 19,
 'on': 20,
 'not': 21,
 'you': 22,
 'are': 23,
 'his': 24,
 'have': 25,
 'be': 26,
 'one': 27,
 'he': 28,
 'all': 29,
 'at': 30,
 'by': 31,
 'an': 32,
 'they': 33,
 'so': 34,
 'from': 35,
 'who': 36,
 'like': 37,
 'or': 38,
 'just': 39,
 'her': 40,
 'out': 41,
 'about': 42,
 'if': 43,
 "it's": 44,
 'has': 45,
 'there': 46,
 'some': 47,
 'what': 48,
 'good': 49,
 'more': 50,
 'very': 51,
 'when': 52,
 'up': 53,
 'no': 54,
 'time': 55,
 'my': 56,
 'even': 57,
 'she': 58,
 'would': 59,
 'which': 60,
 'only': 61,
 'story': 62,
 'really': 63,
 'see': 64,
 'their': 65,
 'had': 66,
 'can': 67,
 'me': 68,
 'well': 69,
 'were': 70,
 'we': 71,
 'than': 72,
 'much': 73,
 'bad': 74,
 'been': 75,
 'do': 76,
 'get': 77,
 'great': 78,
 'also': 79,
 'will': 80,
 'other': 81,
 'into': 82,
 'p

In [26]:
train_sequences = pad_sequences(train_sequences, maxlen=150)
test_sequences = pad_sequences(test_sequences, maxlen=150)

In [29]:
train_sequences[5]

array([   0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,   10,   89,  118,   86,   11,   17, 1972,   34,
        107, 1152,  825,   20,   11, 2060,  144,    3,  193,  323,    2,
        235,   51, 1083,   16,    1,   62,   11, 6290,  209,   19,  666,
       2614,   18,   57,   43,   10,  291,    1,  333,  112,   51,  333,
       1054, 1897,   14,    1,  511, 8445,    2,   29,  183, 2136, 5314,
          1, 4286,  337, 3910,    2, 1377, 1247,  486, 5483,   11, 4407,
       1179, 1722,  295, 3385,   41,   86, 1032,   12,  349,   13,   43,
         22,  339,   12,    2,  187,   12,   13, 1059,  757, 3583, 1055,
          9,  237,   13,    1,   88, 5013,  154,  173,    4,    1,   17,
        272,  466,   37,   11,   17,   18,   43,  338,    3,  323,   38,
         21,  337, 2061,   89,   64,    9,  590], d

In [32]:
# sequential models mean layers are defined in order
mod = keras.models.Sequential([
      # embeddings are neural network layers that map word indices to weights. same size as length of word index
      keras.layers.Embedding(10000, 25, input_length=150),
      # flatten reshapes the date to two dimensions
      keras.layers.Flatten(),
      # this multiplies the data from the word embedding onto another set of weights
      keras.layers.Dense(50, activation="relu"),
      # 1 refers to the number of predictions we want to make
      # Dense layers are usual the last layer inside the neural network
      keras.layers.Dense(1, activation="sigmoid")
])

In [34]:
mod.summary()

Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding_1 (Embedding)      (None, 150, 25)           250000    
_________________________________________________________________
flatten_1 (Flatten)          (None, 3750)              0         
_________________________________________________________________
dense_1 (Dense)              (None, 50)                187550    
_________________________________________________________________
dense_2 (Dense)              (None, 1)                 51        
Total params: 437,601
Trainable params: 437,601
Non-trainable params: 0
_________________________________________________________________


In [37]:
a = np.arange(20).reshape(5, 4)
b = np.arange(20).reshape(4, 5)

In [38]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [39]:
b

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [40]:
a.dot(b)

array([[ 70,  76,  82,  88,  94],
       [190, 212, 234, 256, 278],
       [310, 348, 386, 424, 462],
       [430, 484, 538, 592, 646],
       [550, 620, 690, 760, 830]])

In [41]:
a[1, :]

array([4, 5, 6, 7])

In [43]:
b[:, 0]

array([ 0,  5, 10, 15])

In [45]:
a[1, :]*b[:, 0]

array([  0,  25,  60, 105])

In [46]:
np.sum(a[1, :]*b[:, 0])

190

In [47]:
np.sum(a[2, :]*b[:, 2])

386

In [50]:
# conmpile specifies how your model will be trained
# optimizer -- how do you update the weights? will usually work with adam
# loss -- how does the model fit itself? binary_crossentropy = standard loss for binary clasification
mod.compile(optimizer="adam", loss="binary_crossentropy", metrics=["acc"])

In [52]:
# keras only works with numpy arrays
mod.fit(train_sequences, y_train.values, validation_split=0.2, epochs=10)

Epoch 1/10
1000/1000 [==============================] - 8s 8ms/step - loss: 0.1399 - acc: 0.9486 - val_loss: 0.1530 - val_acc: 0.9414
Epoch 2/10
1000/1000 [==============================] - 8s 8ms/step - loss: 0.0251 - acc: 0.9933 - val_loss: 0.1814 - val_acc: 0.9404
Epoch 3/10
1000/1000 [==============================] - 8s 8ms/step - loss: 0.0043 - acc: 0.9992 - val_loss: 0.2256 - val_acc: 0.9419
Epoch 4/10
1000/1000 [==============================] - 8s 8ms/step - loss: 5.9550e-04 - acc: 1.0000 - val_loss: 0.2384 - val_acc: 0.9431
Epoch 5/10
1000/1000 [==============================] - 8s 8ms/step - loss: 1.2900e-04 - acc: 1.0000 - val_loss: 0.2499 - val_acc: 0.9431
Epoch 6/10
1000/1000 [==============================] - 8s 8ms/step - loss: 6.5249e-05 - acc: 1.0000 - val_loss: 0.2608 - val_acc: 0.9433
Epoch 7/10
1000/1000 [==============================] - 8s 8ms/step - loss: 3.6820e-05 - acc: 1.0000 - val_loss: 0.2717 - val_acc: 0.9430
Epoch 8/10
1000/1000 [========================