In [1]:
cd

/Users/imac


In [62]:
import pandas as pd
import numpy as np

In [63]:
df = pd.read_csv("/Users/imac/DAT07-28-AG/ClassMaterial/Unit3/data/housing.csv")

In [64]:
df.head()

CRIM    ZN  INDUS  CHAS    NOX     RM   AGE     DIS  RAD  TAX  PTRATIO  \
0  0.00632  18.0   2.31     0  0.538  6.575  65.2  4.0900    1  296     15.3   
1  0.02731   0.0   7.07     0  0.469  6.421  78.9  4.9671    2  242     17.8   
2  0.02729   0.0   7.07     0  0.469  7.185  61.1  4.9671    2  242     17.8   
3  0.03237   0.0   2.18     0  0.458  6.998  45.8  6.0622    3  222     18.7   
4  0.06905   0.0   2.18     0  0.458  7.147  54.2  6.0622    3  222     18.7   

        B  LSTAT  PRICE  
0  396.90   4.98   24.0  
1  396.90   9.14   21.6  
2  392.83   4.03   34.7  
3  394.63   2.94   33.4  
4  396.90   5.33   36.2

In [15]:
def average_accuracy(df):
    prediction = df["PRICE"].mean()
    average_accuracy = np.mean(np.abs(df["PRICE"] - prediction))
    return average_accuracy

In [8]:
df["PRICE"] - df["PRICE"].mean()

0       1.467194
1      -0.932806
2      12.167194
3      10.867194
4      13.667194
         ...    
501    -0.132806
502    -1.932806
503     1.367194
504    -0.532806
505   -10.632806
Name: PRICE, Length: 506, dtype: float64

In [10]:
np.abs(df["PRICE"] - df["PRICE"].mean())

0       1.467194
1       0.932806
2      12.167194
3      10.867194
4      13.667194
         ...    
501     0.132806
502     1.932806
503     1.367194
504     0.532806
505    10.632806
Name: PRICE, Length: 506, dtype: float64

In [11]:
np.mean(np.abs(df["PRICE"] - df["PRICE"].mean()))

6.64720742395601

In [13]:
average_accuracy(df)

6.64720742395601

In [16]:
df["CHAS"].unique()

array([0, 1])

In [28]:
left_split = df[df.LSTAT < 9.14].copy()
right_split = df[df.LSTAT >= 9.14].copy()

In [18]:
left_split

CRIM    ZN  INDUS  CHAS    NOX     RM   AGE     DIS  RAD  TAX  \
0    0.00632  18.0   2.31     0  0.538  6.575  65.2  4.0900    1  296   
1    0.02731   0.0   7.07     0  0.469  6.421  78.9  4.9671    2  242   
2    0.02729   0.0   7.07     0  0.469  7.185  61.1  4.9671    2  242   
3    0.03237   0.0   2.18     0  0.458  6.998  45.8  6.0622    3  222   
4    0.06905   0.0   2.18     0  0.458  7.147  54.2  6.0622    3  222   
..       ...   ...    ...   ...    ...    ...   ...     ...  ...  ...   
501  0.06263   0.0  11.93     0  0.573  6.593  69.1  2.4786    1  273   
502  0.04527   0.0  11.93     0  0.573  6.120  76.7  2.2875    1  273   
503  0.06076   0.0  11.93     0  0.573  6.976  91.0  2.1675    1  273   
504  0.10959   0.0  11.93     0  0.573  6.794  89.3  2.3889    1  273   
505  0.04741   0.0  11.93     0  0.573  6.030  80.8  2.5050    1  273   

     PTRATIO       B  LSTAT  PRICE  
0       15.3  396.90   4.98   24.0  
1       17.8  396.90   9.14   21.6  
2       17.8  392.83   4.03   34.7  
3       18.7  394.63   2.94   33.4  
4       18.7  396.90   5.33   36.2  
..       ...     ...    ...    ...  
501     21.0  391.99   9.67   22.4  
502     21.0  396.90   9.08   20.6  
503     21.0  396.90   5.64   23.9  
504     21.0  393.45   6.48   22.0  
505     21.0  396.90   7.88   11.9  

[471 rows x 14 columns]

In [19]:
right_split

CRIM    ZN  INDUS  CHAS     NOX     RM    AGE     DIS  RAD  TAX  \
142  3.32105   0.0  19.58     1  0.8710  5.403  100.0  1.3216    5  403   
152  1.12658   0.0  19.58     1  0.8710  5.012   88.0  1.6102    5  403   
154  1.41385   0.0  19.58     1  0.8710  6.129   96.0  1.7494    5  403   
155  3.53501   0.0  19.58     1  0.8710  6.152   82.6  1.7455    5  403   
160  1.27346   0.0  19.58     1  0.6050  6.250   92.6  1.7984    5  403   
162  1.83377   0.0  19.58     1  0.6050  7.802   98.2  2.0407    5  403   
163  1.51902   0.0  19.58     1  0.6050  8.375   93.9  2.1620    5  403   
208  0.13587   0.0  10.59     1  0.4890  6.064   59.1  4.2392    4  277   
209  0.43571   0.0  10.59     1  0.4890  5.344  100.0  3.8750    4  277   
210  0.17446   0.0  10.59     1  0.4890  5.960   92.1  3.8771    4  277   
211  0.37578   0.0  10.59     1  0.4890  5.404   88.6  3.6650    4  277   
212  0.21719   0.0  10.59     1  0.4890  5.807   53.8  3.6526    4  277   
216  0.04560   0.0  13.89     1  0.5500  5.888   56.0  3.1121    5  276   
218  0.11069   0.0  13.89     1  0.5500  5.951   93.8  2.8893    5  276   
219  0.11425   0.0  13.89     1  0.5500  6.373   92.4  3.3633    5  276   
220  0.35809   0.0   6.20     1  0.5070  6.951   88.5  2.8617    8  307   
221  0.40771   0.0   6.20     1  0.5070  6.164   91.3  3.0480    8  307   
222  0.62356   0.0   6.20     1  0.5070  6.879   77.7  3.2721    8  307   
234  0.44791   0.0   6.20     1  0.5070  6.726   66.5  3.6519    8  307   
236  0.52058   0.0   6.20     1  0.5070  6.631   76.5  4.1480    8  307   
269  0.09065  20.0   6.96     1  0.4640  5.920   61.5  3.9175    3  223   
273  0.22188  20.0   6.96     1  0.4640  7.691   51.8  4.3665    3  223   
274  0.05644  40.0   6.41     1  0.4470  6.758   32.9  4.0776    4  254   
276  0.10469  40.0   6.41     1  0.4470  7.267   49.0  4.7872    4  254   
277  0.06127  40.0   6.41     1  0.4470  6.826   27.6  4.8628    4  254   
282  0.06129  20.0   3.33     1  0.4429  7.645   49.7  5.2119    5  216   
283  0.01501  90.0   1.21     1  0.4010  7.923   24.8  5.8850    1  198   
356  8.98296   0.0  18.10     1  0.7700  6.212   97.4  2.1222   24  666   
357  3.84970   0.0  18.10     1  0.7700  6.395   91.0  2.5052   24  666   
358  5.20177   0.0  18.10     1  0.7700  6.127   83.4  2.7227   24  666   
363  4.22239   0.0  18.10     1  0.7700  5.803   89.0  1.9047   24  666   
364  3.47428   0.0  18.10     1  0.7180  8.780   82.9  1.9047   24  666   
369  5.66998   0.0  18.10     1  0.6310  6.683   96.8  1.3567   24  666   
370  6.53876   0.0  18.10     1  0.6310  7.016   97.5  1.2024   24  666   
372  8.26725   0.0  18.10     1  0.6680  5.875   89.6  1.1296   24  666   

     PTRATIO       B  LSTAT  PRICE  
142     14.7  396.90  26.82   13.4  
152     14.7  343.28  12.12   15.3  
154     14.7  321.02  15.12   17.0  
155     14.7   88.01  15.02   15.6  
160     14.7  338.92   5.50   27.0  
162     14.7  389.61   1.92   50.0  
163     14.7  388.45   3.32   50.0  
208     18.6  381.32  14.66   24.4  
209     18.6  396.90  23.09   20.0  
210     18.6  393.25  17.27   21.7  
211     18.6  395.24  23.98   19.3  
212     18.6  390.94  16.03   22.4  
216     16.4  392.80  13.51   23.3  
218     16.4  396.90  17.92   21.5  
219     16.4  393.74  10.50   23.0  
220     17.4  391.70   9.71   26.7  
221     17.4  395.24  21.46   21.7  
222     17.4  390.39   9.93   27.5  
234     17.4  360.20   8.05   29.0  
236     17.4  388.45   9.54   25.1  
269     18.6  391.34  13.65   20.7  
273     18.6  390.77   6.58   35.2  
274     17.6  396.90   3.53   32.4  
276     17.6  389.25   6.05   33.2  
277     17.6  393.45   4.16   33.1  
282     14.9  377.07   3.01   46.0  
283     13.6  395.52   3.16   50.0  
356     20.2  377.73  17.60   17.8  
357     20.2  391.34  13.27   21.7  
358     20.2  395.43  11.48   22.7  
363     20.2  353.04  14.64   16.8  
364     20.2  354.55   5.29   21.9  
369     20.2  375.33   3.73   50.0  
370     20.2  392.05   2.96   50.0  
372     20.2

In [29]:
average_accuracy(left_split)

7.314644399325124

In [30]:
average_accuracy(right_split)

4.198775562347068

In [31]:
df.shape[0]

506

In [32]:
total_size = df.shape[0]
left_size = left_split.shape[0]
right_size = right_split.shape[0]

In [33]:
left_size

187

In [34]:
average_accuracy(df) - (left_size/total_size)*average_accuracy(left_split) - (right_size/total_size)*average_accuracy(right_split)

1.2969151175083562

In [41]:
from sklearn.tree import DecisionTreeRegressor

# you must initialise your algororithm first

tree = DecisionTreeRegressor(max_depth=4)

In [42]:
# declare x and y variables
y = df["PRICE"]
X = df.drop("PRICE", axis=1)

In [43]:
y

0      24.0
1      21.6
2      34.7
3      33.4
4      36.2
       ... 
501    22.4
502    20.6
503    23.9
504    22.0
505    11.9
Name: PRICE, Length: 506, dtype: float64

In [44]:
X

CRIM    ZN  INDUS  CHAS    NOX     RM   AGE     DIS  RAD  TAX  \
0    0.00632  18.0   2.31     0  0.538  6.575  65.2  4.0900    1  296   
1    0.02731   0.0   7.07     0  0.469  6.421  78.9  4.9671    2  242   
2    0.02729   0.0   7.07     0  0.469  7.185  61.1  4.9671    2  242   
3    0.03237   0.0   2.18     0  0.458  6.998  45.8  6.0622    3  222   
4    0.06905   0.0   2.18     0  0.458  7.147  54.2  6.0622    3  222   
..       ...   ...    ...   ...    ...    ...   ...     ...  ...  ...   
501  0.06263   0.0  11.93     0  0.573  6.593  69.1  2.4786    1  273   
502  0.04527   0.0  11.93     0  0.573  6.120  76.7  2.2875    1  273   
503  0.06076   0.0  11.93     0  0.573  6.976  91.0  2.1675    1  273   
504  0.10959   0.0  11.93     0  0.573  6.794  89.3  2.3889    1  273   
505  0.04741   0.0  11.93     0  0.573  6.030  80.8  2.5050    1  273   

     PTRATIO       B  LSTAT  
0       15.3  396.90   4.98  
1       17.8  396.90   9.14  
2       17.8  392.83   4.03  
3       18.7  394.63   2.94  
4       18.7  396.90   5.33  
..       ...     ...    ...  
501     21.0  391.99   9.67  
502     21.0  396.90   9.08  
503     21.0  396.90   5.64  
504     21.0  393.45   6.48  
505     21.0  396.90   7.88  

[506 rows x 13 columns]

In [67]:
def average_accuracy(df):
    prediction = df['PRICE'].mean()
    average_accuracy = np.mean(np.abs(df['PRICE'] - prediction))
    return average_accuracy

In [69]:
average_accuracy(df)

6.64720742395601

In [71]:
df["PRICE"] - df["PRICE"].mean()

0       1.467194
1      -0.932806
2      12.167194
3      10.867194
4      13.667194
         ...    
501    -0.132806
502    -1.932806
503     1.367194
504    -0.532806
505   -10.632806
Name: PRICE, Length: 506, dtype: float64

In [72]:
np.abs(df["PRICE"] - df["PRICE"].mean())

0       1.467194
1       0.932806
2      12.167194
3      10.867194
4      13.667194
         ...    
501     0.132806
502     1.932806
503     1.367194
504     0.532806
505    10.632806
Name: PRICE, Length: 506, dtype: float64

In [73]:
np.mean(np.abs(df["PRICE"] - df["PRICE"].mean()))

6.64720742395601

In [84]:
left_split = df[df.AGE < 61.1].copy()
right_split = df[df.AGE >= 61.1].copy()

In [75]:
left_split

CRIM    ZN  INDUS  CHAS    NOX     RM   AGE     DIS  RAD  TAX  \
0    0.00632  18.0   2.31     0  0.538  6.575  65.2  4.0900    1  296   
2    0.02729   0.0   7.07     0  0.469  7.185  61.1  4.9671    2  242   
3    0.03237   0.0   2.18     0  0.458  6.998  45.8  6.0622    3  222   
4    0.06905   0.0   2.18     0  0.458  7.147  54.2  6.0622    3  222   
5    0.02985   0.0   2.18     0  0.458  6.430  58.7  6.0622    3  222   
..       ...   ...    ...   ...    ...    ...   ...     ...  ...  ...   
482  5.73116   0.0  18.10     0  0.532  7.061  77.0  3.4106   24  666   
502  0.04527   0.0  11.93     0  0.573  6.120  76.7  2.2875    1  273   
503  0.06076   0.0  11.93     0  0.573  6.976  91.0  2.1675    1  273   
504  0.10959   0.0  11.93     0  0.573  6.794  89.3  2.3889    1  273   
505  0.04741   0.0  11.93     0  0.573  6.030  80.8  2.5050    1  273   

     PTRATIO       B  LSTAT  PRICE  
0       15.3  396.90   4.98   24.0  
2       17.8  392.83   4.03   34.7  
3       18.7  394.63   2.94   33.4  
4       18.7  396.90   5.33   36.2  
5       18.7  394.12   5.21   28.7  
..       ...     ...    ...    ...  
482     20.2  395.28   7.01   25.0  
502     21.0  396.90   9.08   20.6  
503     21.0  396.90   5.64   23.9  
504     21.0  393.45   6.48   22.0  
505     21.0  396.90   7.88   11.9  

[187 rows x 14 columns]

In [76]:
right_split

CRIM    ZN  INDUS  CHAS    NOX     RM    AGE     DIS  RAD  TAX  \
1    0.02731   0.0   7.07     0  0.469  6.421   78.9  4.9671    2  242   
6    0.08829  12.5   7.87     0  0.524  6.012   66.6  5.5605    5  311   
7    0.14455  12.5   7.87     0  0.524  6.172   96.1  5.9505    5  311   
8    0.21124  12.5   7.87     0  0.524  5.631  100.0  6.0821    5  311   
9    0.17004  12.5   7.87     0  0.524  6.004   85.9  6.5921    5  311   
..       ...   ...    ...   ...    ...    ...    ...     ...  ...  ...   
497  0.26838   0.0   9.69     0  0.585  5.794   70.6  2.8927    6  391   
498  0.23912   0.0   9.69     0  0.585  6.019   65.3  2.4091    6  391   
499  0.17783   0.0   9.69     0  0.585  5.569   73.5  2.3999    6  391   
500  0.22438   0.0   9.69     0  0.585  6.027   79.7  2.4982    6  391   
501  0.06263   0.0  11.93     0  0.573  6.593   69.1  2.4786    1  273   

     PTRATIO       B  LSTAT  PRICE  
1       17.8  396.90   9.14   21.6  
6       15.2  395.60  12.43   22.9  
7       15.2  396.90  19.15   27.1  
8       15.2  386.63  29.93   16.5  
9       15.2  386.71  17.10   18.9  
..       ...     ...    ...    ...  
497     19.2  396.90  14.10   18.3  
498     19.2  396.90  12.92   21.2  
499     19.2  395.77  15.10   17.5  
500     19.2  396.90  14.33   16.8  
501     21.0  391.99   9.67   22.4  

[319 rows x 14 columns]

In [77]:
total_size = df.shape[0]
left_size  = left_split.shape[0]
right_size = right_split.shape[0]

In [78]:
total_size

506

In [79]:
average_accuracy(left_split)

7.314644399325124

In [80]:
average_accuracy(right_split)

4.198775562347068

In [85]:
average_accuracy(df) - (left_size/total_size)*average_accuracy(left_split) - (right_size/total_size)*average_accuracy(right_split)

0.3831906431028562

In [86]:
from sklearn.tree import DecisionTreeRegressor

In [87]:
tree = DecisionTreeRegressor(max_depth=4)

In [88]:
# Declare X & y
X = df.drop("PRICE", axis=1)
y = df["PRICE"]

In [89]:
tree.fit(X, y)

DecisionTreeRegressor(max_depth=4)

In [90]:
from prep import draw_tree

In [91]:
draw_tree(tree, X)

NameError: name 'export_graphviz' is not defined

In [92]:
tree.predict(X[:1])

array([27.42727273])

In [93]:
tree = DecisionTreeRegressor(max_depth=3)

In [94]:
# start with a guess
prediction = y.mean()

In [95]:
prediction

22.532806324110698

In [96]:
y - y.mean()

0       1.467194
1      -0.932806
2      12.167194
3      10.867194
4      13.667194
         ...    
501    -0.132806
502    -1.932806
503     1.367194
504    -0.532806
505   -10.632806
Name: PRICE, Length: 506, dtype: float64

In [97]:
gradient = y - y.mean()

In [98]:
gradient

0       1.467194
1      -0.932806
2      12.167194
3      10.867194
4      13.667194
         ...    
501    -0.132806
502    -1.932806
503     1.367194
504    -0.532806
505   -10.632806
Name: PRICE, Length: 506, dtype: float64

In [99]:
tree.fit(X, gradient)

DecisionTreeRegressor(max_depth=3)

In [100]:
tree.predict(X)

array([  0.37239368,   0.37239368,  10.81603089,  10.81603089,
        10.81603089,   0.37239368,   0.37239368,  -5.39518256,
        -5.39518256,  -5.39518256,  -5.39518256,   0.37239368,
        -5.39518256,   0.37239368,   0.37239368,   0.37239368,
         0.37239368,  -5.39518256,   0.37239368,   0.37239368,
        -5.39518256,   0.37239368,  -5.39518256,  -5.39518256,
        -5.39518256,  -5.39518256,  -5.39518256,  -5.39518256,
         0.37239368,   0.37239368,  -5.39518256,   0.37239368,
        -5.39518256,  -5.39518256,  -5.39518256,   0.37239368,
         0.37239368,   0.37239368,   0.37239368,   0.37239368,
        10.81603089,   0.37239368,   0.37239368,   0.37239368,
         0.37239368,   0.37239368,   0.37239368,  -5.39518256,
        -5.39518256,  -5.39518256,   0.37239368,   0.37239368,
         0.37239368,   0.37239368,  -5.39518256,  10.81603089,
         0.37239368,   0.37239368,   0.37239368,   0.37239368,
         0.37239368,  -5.39518256,   0.37239368,   0.37

In [101]:
prediction -= tree.predict(X)

In [102]:
prediction

array([22.16041265, 22.16041265, 11.71677544, 11.71677544, 11.71677544,
       22.16041265, 22.16041265, 27.92798889, 27.92798889, 27.92798889,
       27.92798889, 22.16041265, 27.92798889, 22.16041265, 22.16041265,
       22.16041265, 22.16041265, 27.92798889, 22.16041265, 22.16041265,
       27.92798889, 22.16041265, 27.92798889, 27.92798889, 27.92798889,
       27.92798889, 27.92798889, 27.92798889, 22.16041265, 22.16041265,
       27.92798889, 22.16041265, 27.92798889, 27.92798889, 27.92798889,
       22.16041265, 22.16041265, 22.16041265, 22.16041265, 22.16041265,
       11.71677544, 22.16041265, 22.16041265, 22.16041265, 22.16041265,
       22.16041265, 22.16041265, 27.92798889, 27.92798889, 27.92798889,
       22.16041265, 22.16041265, 22.16041265, 22.16041265, 27.92798889,
       11.71677544, 22.16041265, 22.16041265, 22.16041265, 22.16041265,
       22.16041265, 27.92798889, 22.16041265, 22.16041265, 11.71677544,
       22.16041265, 22.16041265, 22.16041265, 22.16041265, 22.16

In [104]:
gradient = y - prediction

In [105]:
tree.fit(X, gradient)

DecisionTreeRegressor(max_depth=3)

In [107]:
tree.predict(X)

array([  0.74478735,   0.74478735,  21.63206177,  21.63206177,
        21.63206177,   0.74478735,   0.74478735, -10.79036512,
       -10.79036512, -10.79036512, -10.79036512,   0.74478735,
       -10.79036512,   0.74478735,   0.74478735,   0.74478735,
         0.74478735, -10.79036512,   0.74478735,   0.74478735,
       -10.79036512,   0.74478735, -10.79036512, -10.79036512,
       -10.79036512, -10.79036512, -10.79036512, -10.79036512,
         0.74478735,   0.74478735, -10.79036512,   0.74478735,
       -10.79036512, -10.79036512, -10.79036512,   0.74478735,
         0.74478735,   0.74478735,   0.74478735,   0.74478735,
        21.63206177,   0.74478735,   0.74478735,   0.74478735,
         0.74478735,   0.74478735,   0.74478735, -10.79036512,
       -10.79036512, -10.79036512,   0.74478735,   0.74478735,
         0.74478735,   0.74478735, -10.79036512,  21.63206177,
         0.74478735,   0.74478735,   0.74478735,   0.74478735,
         0.74478735, -10.79036512,   0.74478735,   0.74

In [108]:
prediction -= tree.predict(X)

In [109]:
prediction

array([ 21.4156253 ,  21.4156253 ,  -9.91528633,  -9.91528633,
        -9.91528633,  21.4156253 ,  21.4156253 ,  38.71835401,
        38.71835401,  38.71835401,  38.71835401,  21.4156253 ,
        38.71835401,  21.4156253 ,  21.4156253 ,  21.4156253 ,
        21.4156253 ,  38.71835401,  21.4156253 ,  21.4156253 ,
        38.71835401,  21.4156253 ,  38.71835401,  38.71835401,
        38.71835401,  38.71835401,  38.71835401,  38.71835401,
        21.4156253 ,  21.4156253 ,  38.71835401,  21.4156253 ,
        38.71835401,  38.71835401,  38.71835401,  21.4156253 ,
        21.4156253 ,  21.4156253 ,  21.4156253 ,  21.4156253 ,
        -9.91528633,  21.4156253 ,  21.4156253 ,  21.4156253 ,
        21.4156253 ,  21.4156253 ,  21.4156253 ,  38.71835401,
        38.71835401,  38.71835401,  21.4156253 ,  21.4156253 ,
        21.4156253 ,  21.4156253 ,  38.71835401,  -9.91528633,
        21.4156253 ,  21.4156253 ,  21.4156253 ,  21.4156253 ,
        21.4156253 ,  38.71835401,  21.4156253 ,  21.41

In [112]:
gradient = y - prediction

In [113]:
gradient 

0       2.584375
1       0.184375
2      44.615286
3      43.315286
4      46.115286
         ...    
501     0.984375
502    -0.815625
503    33.815286
504     0.584375
505    -9.515625
Name: PRICE, Length: 506, dtype: float64

In [114]:
learning_rate = .01

In [115]:
gradient * learning_rate

0      0.025844
1      0.001844
2      0.446153
3      0.433153
4      0.461153
         ...   
501    0.009844
502   -0.008156
503    0.338153
504    0.005844
505   -0.095156
Name: PRICE, Length: 506, dtype: float64

In [116]:
prediction -= (gradient * learning_rate)

In [117]:
prediction

0      21.389782
1      21.413782
2     -10.361439
3     -10.348439
4     -10.376439
         ...    
501    21.405782
502    21.423782
503   -10.253439
504    21.409782
505    21.510782
Name: PRICE, Length: 506, dtype: float64

In [118]:
from sklearn.ensemble import GradientBoostingRegressor

In [119]:
gbm = GradientBoostingRegressor()

In [120]:
gbm

GradientBoostingRegressor()

In [121]:
gbm.fit(X, y)

GradientBoostingRegressor()

In [124]:
df["Prediction"] = gbm.predict(X)

In [125]:
df.head()

CRIM    ZN  INDUS  CHAS    NOX     RM   AGE     DIS  RAD  TAX  PTRATIO  \
0  0.00632  18.0   2.31     0  0.538  6.575  65.2  4.0900    1  296     15.3   
1  0.02731   0.0   7.07     0  0.469  6.421  78.9  4.9671    2  242     17.8   
2  0.02729   0.0   7.07     0  0.469  7.185  61.1  4.9671    2  242     17.8   
3  0.03237   0.0   2.18     0  0.458  6.998  45.8  6.0622    3  222     18.7   
4  0.06905   0.0   2.18     0  0.458  7.147  54.2  6.0622    3  222     18.7   

        B  LSTAT  PRICE  Prediction  
0  396.90   4.98   24.0   25.907726  
1  396.90   9.14   21.6   21.963202  
2  392.83   4.03   34.7   33.927122  
3  394.63   2.94   33.4   34.145281  
4  396.90   5.33   36.2   35.412679

In [126]:
gbm.score(X, y)

0.9761405838418584

In [128]:
gbm.get_params()

{'alpha': 0.9,
 'ccp_alpha': 0.0,
 'criterion': 'friedman_mse',
 'init': None,
 'learning_rate': 0.1,
 'loss': 'ls',
 'max_depth': 3,
 'max_features': None,
 'max_leaf_nodes': None,
 'min_impurity_decrease': 0.0,
 'min_impurity_split': None,
 'min_samples_leaf': 1,
 'min_samples_split': 2,
 'min_weight_fraction_leaf': 0.0,
 'n_estimators': 100,
 'n_iter_no_change': None,
 'presort': 'deprecated',
 'random_state': None,
 'subsample': 1.0,
 'tol': 0.0001,
 'validation_fraction': 0.1,
 'verbose': 0,
 'warm_start': False}