In [1]:
import pandas as pd
import numpy as np
from sklearn.ensemble import GradientBoostingRegressor
from sklearn.tree import DecisionTreeRegressor

In [2]:
df = pd.read_csv("/Users/imac/DAT07-28-AG/ClassMaterial/Unit3/data/iowa_train.csv")

In [3]:
df.head()

Id  MSSubClass  LotArea  OverallQual  OverallCond  YearBuilt  GrLivArea  \
0   1          60     8450            7            5       2003       1710   
1   2          20     9600            6            8       1976       1262   
2   3          60    11250            7            5       2001       1786   
3   4          70     9550            7            5       1915       1717   
4   5          60    14260            8            5       2000       2198   

   1stFlrSF  2ndFlrSF  GrLivArea.1  FullBath  HalfBath  GarageCars  SalePrice  
0       856       854         1710         2         1           2     208500  
1      1262         0         1262         2         0           2     181500  
2       920       866         1786         2         1           2     223500  
3       961       756         1717         1         0           3     140000  
4      1145      1053         2198         2         1           3     250000

In [4]:
gbm = GradientBoostingRegressor()
tree = DecisionTreeRegressor(max_depth=3)

In [31]:
X = df.drop("SalePrice", axis=1)
y = df["SalePrice"]

In [32]:
prediction = y.mean()

In [33]:
prediction

180921.19589041095

In [34]:
# this is the gradient / "error column"
y - prediction

0       27578.80411
1         578.80411
2       42578.80411
3      -40921.19589
4       69078.80411
           ...     
1455    -5921.19589
1456    29078.80411
1457    85578.80411
1458   -38796.19589
1459   -33421.19589
Name: SalePrice, Length: 1460, dtype: float64

In [35]:
gradient = y - prediction 

In [36]:
# fit a tree on the dataset with the errors on the initial prediction
tree.fit(X, gradient)

DecisionTreeRegressor(max_depth=3)

In [37]:
# not the value of the house, but the value of the error of the house price
# answer = prediction + error
tree.predict(X)

array([ 13317.54887946, -56013.41752162,  13317.54887946, ...,
        67059.79160959, -56013.41752162, -56013.41752162])

In [38]:
# takes errors and add to the previous prediction
prediction += tree.predict(X)

In [39]:
prediction

array([194238.74476987, 124907.77836879, 194238.74476987, ...,
       247980.9875    , 124907.77836879, 124907.77836879])

In [40]:
# repeat 
gradient = y - prediction

In [41]:
gradient

0       14261.255230
1       56592.221631
2       29261.255230
3      -54238.744770
4      -64894.553846
            ...     
1455     9533.910920
1456    44533.910920
1457    18519.012500
1458    17217.221631
1459    22592.221631
Name: SalePrice, Length: 1460, dtype: float64

In [42]:
tree.fit(X, gradient)

DecisionTreeRegressor(max_depth=3)

In [43]:
tree.predict(X)

array([ 3481.80411017,  3481.80411017,  3481.80411017, ...,
       41112.68911583,  3481.80411017,  3481.80411017])

In [44]:
prediction += tree.predict(X)

In [45]:
prediction

array([197720.54888005, 128389.58247897, 197720.54888005, ...,
       289093.67661583, 128389.58247897, 128389.58247897])

In [46]:
gradient = y - prediction

In [47]:
tree.fit(X, gradient)

DecisionTreeRegressor(max_depth=3)

In [48]:
tree.predict(X)

array([-8642.66301841,  2598.39298121, -8642.66301841, ...,
       -8642.66301841,  2598.39298121,  2598.39298121])

In [49]:
prediction += tree.predict(X)

In [50]:
prediction

array([189077.88586164, 130987.97546018, 189077.88586164, ...,
       280451.01359742, 130987.97546018, 130987.97546018])

In [22]:
gbm

GradientBoostingRegressor()

In [23]:
gbm.fit(X, y)

GradientBoostingRegressor()