In [1]:
import pandas as pd
import numpy as np
from sklearn.ensemble import GradientBoostingRegressor
from sklearn.tree import DecisionTreeRegressor

In [2]:
df = pd.read_csv("/Users/imac/DAT07-28-AG/ClassMaterial/Unit3/data/iowa_train.csv")

In [3]:
df.head()

Id  MSSubClass  LotArea  OverallQual  OverallCond  YearBuilt  GrLivArea  \
0   1          60     8450            7            5       2003       1710   
1   2          20     9600            6            8       1976       1262   
2   3          60    11250            7            5       2001       1786   
3   4          70     9550            7            5       1915       1717   
4   5          60    14260            8            5       2000       2198   

   1stFlrSF  2ndFlrSF  GrLivArea.1  FullBath  HalfBath  GarageCars  SalePrice  
0       856       854         1710         2         1           2     208500  
1      1262         0         1262         2         0           2     181500  
2       920       866         1786         2         1           2     223500  
3       961       756         1717         1         0           3     140000  
4      1145      1053         2198         2         1           3     250000

In [4]:
gbm = GradientBoostingRegressor()
tree = DecisionTreeRegressor(max_depth=3)

In [31]:
X = df.drop("SalePrice", axis=1)
y = df["SalePrice"]

In [32]:
prediction = y.mean()

In [33]:
prediction

180921.19589041095

In [34]:
# this is the gradient / "error column"
y - prediction

0       27578.80411
1         578.80411
2       42578.80411
3      -40921.19589
4       69078.80411
           ...     
1455    -5921.19589
1456    29078.80411
1457    85578.80411
1458   -38796.19589
1459   -33421.19589
Name: SalePrice, Length: 1460, dtype: float64

In [35]:
gradient = y - prediction 

In [36]:
# fit a tree on the dataset with the errors on the initial prediction
tree.fit(X, gradient)

DecisionTreeRegressor(max_depth=3)

In [37]:
# not the value of the house, but the value of the error of the house price
# answer = prediction + error
tree.predict(X)

array([ 13317.54887946, -56013.41752162,  13317.54887946, ...,
        67059.79160959, -56013.41752162, -56013.41752162])

In [38]:
# takes errors and add to the previous prediction
prediction += tree.predict(X)

In [39]:
prediction

array([194238.74476987, 124907.77836879, 194238.74476987, ...,
       247980.9875    , 124907.77836879, 124907.77836879])

In [40]:
# repeat 
gradient = y - prediction

In [41]:
gradient

0       14261.255230
1       56592.221631
2       29261.255230
3      -54238.744770
4      -64894.553846
            ...     
1455     9533.910920
1456    44533.910920
1457    18519.012500
1458    17217.221631
1459    22592.221631
Name: SalePrice, Length: 1460, dtype: float64

In [42]:
tree.fit(X, gradient)

DecisionTreeRegressor(max_depth=3)

In [43]:
tree.predict(X)

array([ 3481.80411017,  3481.80411017,  3481.80411017, ...,
       41112.68911583,  3481.80411017,  3481.80411017])

In [44]:
prediction += tree.predict(X)

In [45]:
prediction

array([197720.54888005, 128389.58247897, 197720.54888005, ...,
       289093.67661583, 128389.58247897, 128389.58247897])

In [46]:
gradient = y - prediction

In [47]:
tree.fit(X, gradient)

DecisionTreeRegressor(max_depth=3)

In [48]:
tree.predict(X)

array([-8642.66301841,  2598.39298121, -8642.66301841, ...,
       -8642.66301841,  2598.39298121,  2598.39298121])

In [49]:
prediction += tree.predict(X)

In [50]:
prediction

array([189077.88586164, 130987.97546018, 189077.88586164, ...,
       280451.01359742, 130987.97546018, 130987.97546018])

In [22]:
gbm

GradientBoostingRegressor()

In [23]:
gbm.fit(X, y)

GradientBoostingRegressor()

In [51]:
train = pd.read_csv("/Users/imac/DAT07-28-AG/ClassMaterial/Unit3/data/iowa_train2.csv")

In [52]:
train.head()

Id  MSSubClass MSZoning  LotArea Neighborhood  OverallQual  OverallCond  \
0   1          60       RL     8450      CollgCr            7            5   
1   2          20       RL     9600      Veenker            6            8   
2   3          60       RL    11250      CollgCr            7            5   
3   4          70       RL     9550      Crawfor            7            5   
4   5          60       RL    14260      NoRidge            8            5   

   YearBuilt  GrLivArea  1stFlrSF  2ndFlrSF  GrLivArea.1  FullBath  HalfBath  \
0       2003       1710       856       854         1710         2         1   
1       1976       1262      1262         0         1262         2         0   
2       2001       1786       920       866         1786         2         1   
3       1915       1717       961       756         1717         1         0   
4       2000       2198      1145      1053         2198         2         1   

  GarageType  GarageYrBlt GarageFinish  GarageCars  SalePrice  
0     Attchd       2003.0          RFn           2     208500  
1     Attchd       1976.0          RFn           2     181500  
2     Attchd       2001.0          RFn           2     223500  
3     Detchd       1998.0          Unf           3     140000  
4     Attchd       2000.0          RFn           3     250000

In [58]:
train.loc[:, train.isnull().sum() > 0].isnull().corr()

GarageType  GarageYrBlt  GarageFinish
GarageType           1.0          1.0           1.0
GarageYrBlt          1.0          1.0           1.0
GarageFinish         1.0          1.0           1.0

In [59]:
train["GarageType"].unique()

array(['Attchd', 'Detchd', 'BuiltIn', 'CarPort', nan, 'Basment', '2Types'],
      dtype=object)

In [ ]:
train.loc[:, train]

In [60]:
def denote_null_values(train):
    empty_cols_query = train.isnull().sum() > 0
    empty_train_cols = train.loc[:, empty_cols_query].columns.tolist()
    for col in empty_train_cols:
        col_name = f"{col}_missing"
        train[col_name] = pd.isnull(train[col])
    return train

In [63]:
train = denote_null_values(train)

In [64]:
train.head()

Id  MSSubClass MSZoning  LotArea Neighborhood  OverallQual  OverallCond  \
0   1          60       RL     8450      CollgCr            7            5   
1   2          20       RL     9600      Veenker            6            8   
2   3          60       RL    11250      CollgCr            7            5   
3   4          70       RL     9550      Crawfor            7            5   
4   5          60       RL    14260      NoRidge            8            5   

   YearBuilt  GrLivArea  1stFlrSF  ...  FullBath  HalfBath  GarageType  \
0       2003       1710       856  ...         2         1      Attchd   
1       1976       1262      1262  ...         2         0      Attchd   
2       2001       1786       920  ...         2         1      Attchd   
3       1915       1717       961  ...         1         0      Detchd   
4       2000       2198      1145  ...         2         1      Attchd   

   GarageYrBlt GarageFinish  GarageCars SalePrice  GarageType_missing  \
0       2003.0          RFn           2    208500               False   
1       1976.0          RFn           2    181500               False   
2       2001.0          RFn           2    223500               False   
3       1998.0          Unf           3    140000               False   
4       2000.0          RFn           3    250000               False   

   GarageYrBlt_missing  GarageFinish_missing  
0                False                 False  
1                False                 False  
2                False                 False  
3                False                 False  
4                False                 False  

[5 rows x 22 columns]

In [66]:
train["Neighborhood"]

0       CollgCr
1       Veenker
2       CollgCr
3       Crawfor
4       NoRidge
         ...   
1455    Gilbert
1456     NWAmes
1457    Crawfor
1458      NAmes
1459    Edwards
Name: Neighborhood, Length: 1460, dtype: object

In [67]:
pd.get_dummies(train["Neighborhood"])

Blmngtn  Blueste  BrDale  BrkSide  ClearCr  CollgCr  Crawfor  Edwards  \
0           0        0       0        0        0        1        0        0   
1           0        0       0        0        0        0        0        0   
2           0        0       0        0        0        1        0        0   
3           0        0       0        0        0        0        1        0   
4           0        0       0        0        0        0        0        0   
...       ...      ...     ...      ...      ...      ...      ...      ...   
1455        0        0       0        0        0        0        0        0   
1456        0        0       0        0        0        0        0        0   
1457        0        0       0        0        0        0        1        0   
1458        0        0       0        0        0        0        0        0   
1459        0        0       0        0        0        0        0        1   

      Gilbert  IDOTRR  ...  NoRidge  NridgHt  OldTown  SWISU  Sawyer  SawyerW  \
0           0       0  ...        0        0        0      0       0        0   
1           0       0  ...        0        0        0      0       0        0   
2           0       0  ...        0        0        0      0       0        0   
3           0       0  ...        0        0        0      0       0        0   
4           0       0  ...        1        0        0      0       0        0   
...       ...     ...  ...      ...      ...      ...    ...     ...      ...   
1455        1       0  ...        0        0        0      0       0        0   
1456        0       0  ...        0        0        0      0       0        0   
1457        0       0  ...        0        0        0      0       0        0   
1458        0       0  ...        0        0        0      0       0        0   
1459        0       0  ...        0        0        0      0       0        0   

      Somerst  StoneBr  Timber  Veenker  
0           0        0       0        0  
1           0        0       0        1  
2           0        0       0        0  
3           0        0       0        0  
4           0        0       0        0  
...       ...      ...     ...      ...  
1455        0        0       0        0  
1456        0        0       0        0  
1457        0        0       0        0  
1458        0        0       0        0  
1459        0        0       0        0  

[1460 rows x 25 columns]

In [68]:
pd.get_dummies(train)

Id  MSSubClass  LotArea  OverallQual  OverallCond  YearBuilt  \
0        1          60     8450            7            5       2003   
1        2          20     9600            6            8       1976   
2        3          60    11250            7            5       2001   
3        4          70     9550            7            5       1915   
4        5          60    14260            8            5       2000   
...    ...         ...      ...          ...          ...        ...   
1455  1456          60     7917            6            5       1999   
1456  1457          20    13175            6            6       1978   
1457  1458          70     9042            7            9       1941   
1458  1459          20     9717            5            6       1950   
1459  1460          20     9937            5            6       1965   

      GrLivArea  1stFlrSF  2ndFlrSF  GrLivArea.1  ...  Neighborhood_Veenker  \
0          1710       856       854         1710  ...                     0   
1          1262      1262         0         1262  ...                     1   
2          1786       920       866         1786  ...                     0   
3          1717       961       756         1717  ...                     0   
4          2198      1145      1053         2198  ...                     0   
...         ...       ...       ...          ...  ...                   ...   
1455       1647       953       694         1647  ...                     0   
1456       2073      2073         0         2073  ...                     0   
1457       2340      1188      1152         2340  ...                     0   
1458       1078      1078         0         1078  ...                     0   
1459       1256      1256         0         1256  ...                     0   

      GarageType_2Types  GarageType_Attchd  GarageType_Basment  \
0                     0                  1                   0   
1                     0                  1                   0   
2                     0                  1                   0   
3                     0                  0                   0   
4                     0                  1                   0   
...                 ...                ...                 ...   
1455                  0                  1                   0   
1456                  0                  1                   0   
1457                  0                  1                   0   
1458                  0                  1                   0   
1459                  0                  1                   0   

      GarageType_BuiltIn  GarageType_CarPort  GarageType_Detchd  \
0                      0                   0                  0   
1                      0                   0                  0   
2                      0                   0                  0   
3                      0                   0                  1   
4                      0                   0                  0   
...                  ...                 ...                ...   
1455                   0                   0                  0   
1456                   0                   0                  0   
1457                   0                   0                  0   
1458                   0                   0                  0   
1459                   0                   0                  0   

      GarageFinish_Fin  GarageFinish_RFn  GarageFinish_Unf  
0                    0                 1                 0  
1                    0                 1                 0  
2                    0                 1                 0  
3                    0                 0                 1  
4                    0                 1                 0  
...                ...               ...               ...  
1455                 0                 1                 0  
1456                 0                 0                 1  
1457                 0                 1       

In [70]:
train["Neighborhood"].astype("category").cat.codes

0        5
1       24
2        5
3        6
4       15
        ..
1455     8
1456    14
1457     6
1458    12
1459     7
Length: 1460, dtype: int8

In [71]:
cat_cols = train.select_dtypes(include=np.object).columns.tolist()

In [72]:
cat_cols

['MSZoning', 'Neighborhood', 'GarageType', 'GarageFinish']

In [73]:
train[cat_cols] = train[cat_cols].astype('category')

In [74]:
for col in cat_cols:
    train[col] = train[col].cat.codes

In [75]:
train.head()

Id  MSSubClass  MSZoning  LotArea  Neighborhood  OverallQual  OverallCond  \
0   1          60         3     8450             5            7            5   
1   2          20         3     9600            24            6            8   
2   3          60         3    11250             5            7            5   
3   4          70         3     9550             6            7            5   
4   5          60         3    14260            15            8            5   

   YearBuilt  GrLivArea  1stFlrSF  ...  FullBath  HalfBath  GarageType  \
0       2003       1710       856  ...         2         1           1   
1       1976       1262      1262  ...         2         0           1   
2       2001       1786       920  ...         2         1           1   
3       1915       1717       961  ...         1         0           5   
4       2000       2198      1145  ...         2         1           1   

   GarageYrBlt  GarageFinish  GarageCars  SalePrice  GarageType_missing  \
0       2003.0             1           2     208500               False   
1       1976.0             1           2     181500               False   
2       2001.0             1           2     223500               False   
3       1998.0             2           3     140000               False   
4       2000.0             1           3     250000               False   

   GarageYrBlt_missing  GarageFinish_missing  
0                False                 False  
1                False                 False  
2                False                 False  
3                False                 False  
4                False                 False  

[5 rows x 22 columns]

In [76]:
X_train, X_val, y_train, y_val = X[:1100].copy(), X[1100:].copy(), y[:1100].copy(), y[1100:].copy()

In [77]:
gbm.fit(X_train, y_train)

GradientBoostingRegressor()

In [78]:
gbm.score(X_val, y_val)

0.8816304701296296